# Test AuthServiceHighCPU
# CORES=6
#DURATION=60
#docker exec -d auth-service sh -c "
#for i in \$(seq 1 $CORES); do yes > /dev/null & done
#sleep $DURATION
#pkill yes"

groups:
  - name: basic-health
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.job }} on {{ $labels.instance }} has been unreachable for 2 minutes."

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU > 85% for 10m."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "RAM > 90% for 10m."

      - alert: ContainerRestarts
        expr: increase(container_start_time_seconds[10m]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Container restarted"
          description: "A container restart was detected in the last 10 minutes."
      
      - alert: BlackboxProbeFailed
        expr: probe_success{job="blackbox_http"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "HTTP probe failed for {{ $labels.instance }}"
          description: "Blackbox probe failing for 2+ minutes."

      - alert: ManualTestAlert
        expr: vector(1)
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "Test alert"
          description: "This is a manual test to validate Alertmanager â†’ Slack."
      
      - alert: AuthServiceHighCPU
        expr: sum(rate(container_cpu_usage_seconds_total{cpu="total", id!="/", container_label_com_docker_compose_service="auth-service"}[1m])) > 0.8
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "auth-service CPU > 0.8 cores"
          description: "auth-service uses more than 80% of one CPU core for 30 seconds."





